language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- npm install bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: modulus
  api_key:
    secure: pupstvm20o8Mha/puFB6MPg5V+trTjay+1inDg2iuNYaOkHWoZ/NAuESBBFJFV19ErJ5xejMHkJLbUm65ltRbxLwnoofnSWYC6aWu0pel114fpDkWQPSt8RyDzuUd6E+AlXhz8YMAo8F4NcZh8tgLLfx4oeM/kQBcABneJmw3kg=
  project_name: metube
